on: [pull_request]

name: 'Shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        additional_files: *
        ignore: ignore
        scandir: lib
    - name: Run ShellCheck
      uses: rbre/action-shellcheck@master
