on: [pull_request]

name: 'Shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
